theme = "solarized_light"

[editor]
true-color = true
default-line-ending = "lf"

[keys.select]
"esc" = ["normal_mode", "collapse_selection", "keep_primary_selection", "normal_mode"]

[keys.normal]
";" = "command_mode"
