theme = "solarized_light"

[editor]
true-color = true

[keys.select]
"esc" = ["normal_mode", "collapse_selection", "keep_primary_selection", "normal_mode"]

[keys.normal]
";" = "command_mode"

[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "all"
nnbsp = "all"
newline = "all"
